/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapEventsDotxmlRouteImport } from './routes/sitemap-events[.]xml'
import { Route as SitemapArchiveDotxmlRouteImport } from './routes/sitemap-archive[.]xml'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as Char123LocaleChar125IndexRouteImport } from './routes/{-$locale}/index'
import { Route as Char123LocaleChar125SourcesRouteImport } from './routes/{-$locale}/sources'
import { Route as Char123LocaleChar125LoginRouteImport } from './routes/{-$locale}/login'
import { Route as Char123LocaleChar125HistoryRouteImport } from './routes/{-$locale}/history'
import { Route as Char123LocaleChar125DashboardRouteImport } from './routes/{-$locale}/dashboard'
import { Route as Char123LocaleChar125BriefingsRouteImport } from './routes/{-$locale}/briefings'
import { Route as Char123LocaleChar125AgentsRouteImport } from './routes/{-$locale}/agents'
import { Route as Char123LocaleChar125ViewsRouteImport } from './routes/{-$locale}/_views'
import { Route as DotwellKnownApiCatalogRouteImport } from './routes/[.]well-known.api-catalog'
import { Route as Char123LocaleChar125SourcesIdRouteImport } from './routes/{-$locale}/sources_.$id'
import { Route as Char123LocaleChar125SkillsOpentrendsRouteImport } from './routes/{-$locale}/skills.opentrends'
import { Route as Char123LocaleChar125EventsFlowRouteImport } from './routes/{-$locale}/events_.flow'
import { Route as Char123LocaleChar125EventsSlugRouteImport } from './routes/{-$locale}/events_.$slug'
import { Route as Char123LocaleChar125ViewsTrendsRouteImport } from './routes/{-$locale}/_views/trends'
import { Route as Char123LocaleChar125ViewsFeedRouteImport } from './routes/{-$locale}/_views/feed'
import { Route as Char123LocaleChar125ViewsEventsRouteImport } from './routes/{-$locale}/_views/events'
import { Route as Char123LocaleChar125ViewsCalendarRouteImport } from './routes/{-$locale}/_views/calendar'
import { Route as Char123LocaleChar125ViewsTrendsIndexRouteImport } from './routes/{-$locale}/_views/trends.index'
import { Route as Char123LocaleChar125TrendsTopicArchiveRouteImport } from './routes/{-$locale}/trends.$topic.archive'
import { Route as Char123LocaleChar125TrendsTopicDayRouteImport } from './routes/{-$locale}/trends.$topic.$day'
import { Route as Char123LocaleChar125ViewsTrendsTopicRouteImport } from './routes/{-$locale}/_views/trends.$topic'

const SitemapEventsDotxmlRoute = SitemapEventsDotxmlRouteImport.update({
  id: '/sitemap-events.xml',
  path: '/sitemap-events.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapArchiveDotxmlRoute = SitemapArchiveDotxmlRouteImport.update({
  id: '/sitemap-archive.xml',
  path: '/sitemap-archive.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LocaleChar125IndexRoute =
  Char123LocaleChar125IndexRouteImport.update({
    id: '/{-$locale}/',
    path: '/{-$locale}/',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125SourcesRoute =
  Char123LocaleChar125SourcesRouteImport.update({
    id: '/{-$locale}/sources',
    path: '/{-$locale}/sources',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125LoginRoute =
  Char123LocaleChar125LoginRouteImport.update({
    id: '/{-$locale}/login',
    path: '/{-$locale}/login',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125HistoryRoute =
  Char123LocaleChar125HistoryRouteImport.update({
    id: '/{-$locale}/history',
    path: '/{-$locale}/history',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125DashboardRoute =
  Char123LocaleChar125DashboardRouteImport.update({
    id: '/{-$locale}/dashboard',
    path: '/{-$locale}/dashboard',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125BriefingsRoute =
  Char123LocaleChar125BriefingsRouteImport.update({
    id: '/{-$locale}/briefings',
    path: '/{-$locale}/briefings',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125AgentsRoute =
  Char123LocaleChar125AgentsRouteImport.update({
    id: '/{-$locale}/agents',
    path: '/{-$locale}/agents',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125ViewsRoute =
  Char123LocaleChar125ViewsRouteImport.update({
    id: '/{-$locale}/_views',
    path: '/{-$locale}',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotwellKnownApiCatalogRoute = DotwellKnownApiCatalogRouteImport.update({
  id: '/.well-known/api-catalog',
  path: '/.well-known/api-catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LocaleChar125SourcesIdRoute =
  Char123LocaleChar125SourcesIdRouteImport.update({
    id: '/{-$locale}/sources_/$id',
    path: '/{-$locale}/sources/$id',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125SkillsOpentrendsRoute =
  Char123LocaleChar125SkillsOpentrendsRouteImport.update({
    id: '/{-$locale}/skills/opentrends',
    path: '/{-$locale}/skills/opentrends',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125EventsFlowRoute =
  Char123LocaleChar125EventsFlowRouteImport.update({
    id: '/{-$locale}/events_/flow',
    path: '/{-$locale}/events/flow',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125EventsSlugRoute =
  Char123LocaleChar125EventsSlugRouteImport.update({
    id: '/{-$locale}/events_/$slug',
    path: '/{-$locale}/events/$slug',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125ViewsTrendsRoute =
  Char123LocaleChar125ViewsTrendsRouteImport.update({
    id: '/trends',
    path: '/trends',
    getParentRoute: () => Char123LocaleChar125ViewsRoute,
  } as any)
const Char123LocaleChar125ViewsFeedRoute =
  Char123LocaleChar125ViewsFeedRouteImport.update({
    id: '/feed',
    path: '/feed',
    getParentRoute: () => Char123LocaleChar125ViewsRoute,
  } as any)
const Char123LocaleChar125ViewsEventsRoute =
  Char123LocaleChar125ViewsEventsRouteImport.update({
    id: '/events',
    path: '/events',
    getParentRoute: () => Char123LocaleChar125ViewsRoute,
  } as any)
const Char123LocaleChar125ViewsCalendarRoute =
  Char123LocaleChar125ViewsCalendarRouteImport.update({
    id: '/calendar',
    path: '/calendar',
    getParentRoute: () => Char123LocaleChar125ViewsRoute,
  } as any)
const Char123LocaleChar125ViewsTrendsIndexRoute =
  Char123LocaleChar125ViewsTrendsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => Char123LocaleChar125ViewsTrendsRoute,
  } as any)
const Char123LocaleChar125TrendsTopicArchiveRoute =
  Char123LocaleChar125TrendsTopicArchiveRouteImport.update({
    id: '/{-$locale}/trends/$topic/archive',
    path: '/{-$locale}/trends/$topic/archive',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125TrendsTopicDayRoute =
  Char123LocaleChar125TrendsTopicDayRouteImport.update({
    id: '/{-$locale}/trends/$topic/$day',
    path: '/{-$locale}/trends/$topic/$day',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125ViewsTrendsTopicRoute =
  Char123LocaleChar125ViewsTrendsTopicRouteImport.update({
    id: '/$topic',
    path: '/$topic',
    getParentRoute: () => Char123LocaleChar125ViewsTrendsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/privacy': typeof PrivacyRoute
  '/sitemap-archive.xml': typeof SitemapArchiveDotxmlRoute
  '/sitemap-events.xml': typeof SitemapEventsDotxmlRoute
  '/.well-known/api-catalog': typeof DotwellKnownApiCatalogRoute
  '/{-$locale}': typeof Char123LocaleChar125ViewsRouteWithChildren
  '/{-$locale}/agents': typeof Char123LocaleChar125AgentsRoute
  '/{-$locale}/briefings': typeof Char123LocaleChar125BriefingsRoute
  '/{-$locale}/dashboard': typeof Char123LocaleChar125DashboardRoute
  '/{-$locale}/history': typeof Char123LocaleChar125HistoryRoute
  '/{-$locale}/login': typeof Char123LocaleChar125LoginRoute
  '/{-$locale}/sources': typeof Char123LocaleChar125SourcesRoute
  '/{-$locale}/': typeof Char123LocaleChar125IndexRoute
  '/{-$locale}/calendar': typeof Char123LocaleChar125ViewsCalendarRoute
  '/{-$locale}/events': typeof Char123LocaleChar125ViewsEventsRoute
  '/{-$locale}/feed': typeof Char123LocaleChar125ViewsFeedRoute
  '/{-$locale}/trends': typeof Char123LocaleChar125ViewsTrendsRouteWithChildren
  '/{-$locale}/events/$slug': typeof Char123LocaleChar125EventsSlugRoute
  '/{-$locale}/events/flow': typeof Char123LocaleChar125EventsFlowRoute
  '/{-$locale}/skills/opentrends': typeof Char123LocaleChar125SkillsOpentrendsRoute
  '/{-$locale}/sources/$id': typeof Char123LocaleChar125SourcesIdRoute
  '/{-$locale}/trends/$topic': typeof Char123LocaleChar125ViewsTrendsTopicRoute
  '/{-$locale}/trends/$topic/$day': typeof Char123LocaleChar125TrendsTopicDayRoute
  '/{-$locale}/trends/$topic/archive': typeof Char123LocaleChar125TrendsTopicArchiveRoute
  '/{-$locale}/trends/': typeof Char123LocaleChar125ViewsTrendsIndexRoute
}
export interface FileRoutesByTo {
  '/privacy': typeof PrivacyRoute
  '/sitemap-archive.xml': typeof SitemapArchiveDotxmlRoute
  '/sitemap-events.xml': typeof SitemapEventsDotxmlRoute
  '/.well-known/api-catalog': typeof DotwellKnownApiCatalogRoute
  '/{-$locale}': typeof Char123LocaleChar125IndexRoute
  '/{-$locale}/agents': typeof Char123LocaleChar125AgentsRoute
  '/{-$locale}/briefings': typeof Char123LocaleChar125BriefingsRoute
  '/{-$locale}/dashboard': typeof Char123LocaleChar125DashboardRoute
  '/{-$locale}/history': typeof Char123LocaleChar125HistoryRoute
  '/{-$locale}/login': typeof Char123LocaleChar125LoginRoute
  '/{-$locale}/sources': typeof Char123LocaleChar125SourcesRoute
  '/{-$locale}/calendar': typeof Char123LocaleChar125ViewsCalendarRoute
  '/{-$locale}/events': typeof Char123LocaleChar125ViewsEventsRoute
  '/{-$locale}/feed': typeof Char123LocaleChar125ViewsFeedRoute
  '/{-$locale}/events/$slug': typeof Char123LocaleChar125EventsSlugRoute
  '/{-$locale}/events/flow': typeof Char123LocaleChar125EventsFlowRoute
  '/{-$locale}/skills/opentrends': typeof Char123LocaleChar125SkillsOpentrendsRoute
  '/{-$locale}/sources/$id': typeof Char123LocaleChar125SourcesIdRoute
  '/{-$locale}/trends/$topic': typeof Char123LocaleChar125ViewsTrendsTopicRoute
  '/{-$locale}/trends/$topic/$day': typeof Char123LocaleChar125TrendsTopicDayRoute
  '/{-$locale}/trends/$topic/archive': typeof Char123LocaleChar125TrendsTopicArchiveRoute
  '/{-$locale}/trends': typeof Char123LocaleChar125ViewsTrendsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/privacy': typeof PrivacyRoute
  '/sitemap-archive.xml': typeof SitemapArchiveDotxmlRoute
  '/sitemap-events.xml': typeof SitemapEventsDotxmlRoute
  '/.well-known/api-catalog': typeof DotwellKnownApiCatalogRoute
  '/{-$locale}/_views': typeof Char123LocaleChar125ViewsRouteWithChildren
  '/{-$locale}/agents': typeof Char123LocaleChar125AgentsRoute
  '/{-$locale}/briefings': typeof Char123LocaleChar125BriefingsRoute
  '/{-$locale}/dashboard': typeof Char123LocaleChar125DashboardRoute
  '/{-$locale}/history': typeof Char123LocaleChar125HistoryRoute
  '/{-$locale}/login': typeof Char123LocaleChar125LoginRoute
  '/{-$locale}/sources': typeof Char123LocaleChar125SourcesRoute
  '/{-$locale}/': typeof Char123LocaleChar125IndexRoute
  '/{-$locale}/_views/calendar': typeof Char123LocaleChar125ViewsCalendarRoute
  '/{-$locale}/_views/events': typeof Char123LocaleChar125ViewsEventsRoute
  '/{-$locale}/_views/feed': typeof Char123LocaleChar125ViewsFeedRoute
  '/{-$locale}/_views/trends': typeof Char123LocaleChar125ViewsTrendsRouteWithChildren
  '/{-$locale}/events_/$slug': typeof Char123LocaleChar125EventsSlugRoute
  '/{-$locale}/events_/flow': typeof Char123LocaleChar125EventsFlowRoute
  '/{-$locale}/skills/opentrends': typeof Char123LocaleChar125SkillsOpentrendsRoute
  '/{-$locale}/sources_/$id': typeof Char123LocaleChar125SourcesIdRoute
  '/{-$locale}/_views/trends/$topic': typeof Char123LocaleChar125ViewsTrendsTopicRoute
  '/{-$locale}/trends/$topic/$day': typeof Char123LocaleChar125TrendsTopicDayRoute
  '/{-$locale}/trends/$topic/archive': typeof Char123LocaleChar125TrendsTopicArchiveRoute
  '/{-$locale}/_views/trends/': typeof Char123LocaleChar125ViewsTrendsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/privacy'
    | '/sitemap-archive.xml'
    | '/sitemap-events.xml'
    | '/.well-known/api-catalog'
    | '/{-$locale}'
    | '/{-$locale}/agents'
    | '/{-$locale}/briefings'
    | '/{-$locale}/dashboard'
    | '/{-$locale}/history'
    | '/{-$locale}/login'
    | '/{-$locale}/sources'
    | '/{-$locale}/'
    | '/{-$locale}/calendar'
    | '/{-$locale}/events'
    | '/{-$locale}/feed'
    | '/{-$locale}/trends'
    | '/{-$locale}/events/$slug'
    | '/{-$locale}/events/flow'
    | '/{-$locale}/skills/opentrends'
    | '/{-$locale}/sources/$id'
    | '/{-$locale}/trends/$topic'
    | '/{-$locale}/trends/$topic/$day'
    | '/{-$locale}/trends/$topic/archive'
    | '/{-$locale}/trends/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/privacy'
    | '/sitemap-archive.xml'
    | '/sitemap-events.xml'
    | '/.well-known/api-catalog'
    | '/{-$locale}'
    | '/{-$locale}/agents'
    | '/{-$locale}/briefings'
    | '/{-$locale}/dashboard'
    | '/{-$locale}/history'
    | '/{-$locale}/login'
    | '/{-$locale}/sources'
    | '/{-$locale}/calendar'
    | '/{-$locale}/events'
    | '/{-$locale}/feed'
    | '/{-$locale}/events/$slug'
    | '/{-$locale}/events/flow'
    | '/{-$locale}/skills/opentrends'
    | '/{-$locale}/sources/$id'
    | '/{-$locale}/trends/$topic'
    | '/{-$locale}/trends/$topic/$day'
    | '/{-$locale}/trends/$topic/archive'
    | '/{-$locale}/trends'
  id:
    | '__root__'
    | '/privacy'
    | '/sitemap-archive.xml'
    | '/sitemap-events.xml'
    | '/.well-known/api-catalog'
    | '/{-$locale}/_views'
    | '/{-$locale}/agents'
    | '/{-$locale}/briefings'
    | '/{-$locale}/dashboard'
    | '/{-$locale}/history'
    | '/{-$locale}/login'
    | '/{-$locale}/sources'
    | '/{-$locale}/'
    | '/{-$locale}/_views/calendar'
    | '/{-$locale}/_views/events'
    | '/{-$locale}/_views/feed'
    | '/{-$locale}/_views/trends'
    | '/{-$locale}/events_/$slug'
    | '/{-$locale}/events_/flow'
    | '/{-$locale}/skills/opentrends'
    | '/{-$locale}/sources_/$id'
    | '/{-$locale}/_views/trends/$topic'
    | '/{-$locale}/trends/$topic/$day'
    | '/{-$locale}/trends/$topic/archive'
    | '/{-$locale}/_views/trends/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PrivacyRoute: typeof PrivacyRoute
  SitemapArchiveDotxmlRoute: typeof SitemapArchiveDotxmlRoute
  SitemapEventsDotxmlRoute: typeof SitemapEventsDotxmlRoute
  DotwellKnownApiCatalogRoute: typeof DotwellKnownApiCatalogRoute
  Char123LocaleChar125ViewsRoute: typeof Char123LocaleChar125ViewsRouteWithChildren
  Char123LocaleChar125AgentsRoute: typeof Char123LocaleChar125AgentsRoute
  Char123LocaleChar125BriefingsRoute: typeof Char123LocaleChar125BriefingsRoute
  Char123LocaleChar125DashboardRoute: typeof Char123LocaleChar125DashboardRoute
  Char123LocaleChar125HistoryRoute: typeof Char123LocaleChar125HistoryRoute
  Char123LocaleChar125LoginRoute: typeof Char123LocaleChar125LoginRoute
  Char123LocaleChar125SourcesRoute: typeof Char123LocaleChar125SourcesRoute
  Char123LocaleChar125IndexRoute: typeof Char123LocaleChar125IndexRoute
  Char123LocaleChar125EventsSlugRoute: typeof Char123LocaleChar125EventsSlugRoute
  Char123LocaleChar125EventsFlowRoute: typeof Char123LocaleChar125EventsFlowRoute
  Char123LocaleChar125SkillsOpentrendsRoute: typeof Char123LocaleChar125SkillsOpentrendsRoute
  Char123LocaleChar125SourcesIdRoute: typeof Char123LocaleChar125SourcesIdRoute
  Char123LocaleChar125TrendsTopicDayRoute: typeof Char123LocaleChar125TrendsTopicDayRoute
  Char123LocaleChar125TrendsTopicArchiveRoute: typeof Char123LocaleChar125TrendsTopicArchiveRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap-events.xml': {
      id: '/sitemap-events.xml'
      path: '/sitemap-events.xml'
      fullPath: '/sitemap-events.xml'
      preLoaderRoute: typeof SitemapEventsDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-archive.xml': {
      id: '/sitemap-archive.xml'
      path: '/sitemap-archive.xml'
      fullPath: '/sitemap-archive.xml'
      preLoaderRoute: typeof SitemapArchiveDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/': {
      id: '/{-$locale}/'
      path: '/{-$locale}'
      fullPath: '/{-$locale}/'
      preLoaderRoute: typeof Char123LocaleChar125IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/sources': {
      id: '/{-$locale}/sources'
      path: '/{-$locale}/sources'
      fullPath: '/{-$locale}/sources'
      preLoaderRoute: typeof Char123LocaleChar125SourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/login': {
      id: '/{-$locale}/login'
      path: '/{-$locale}/login'
      fullPath: '/{-$locale}/login'
      preLoaderRoute: typeof Char123LocaleChar125LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/history': {
      id: '/{-$locale}/history'
      path: '/{-$locale}/history'
      fullPath: '/{-$locale}/history'
      preLoaderRoute: typeof Char123LocaleChar125HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/dashboard': {
      id: '/{-$locale}/dashboard'
      path: '/{-$locale}/dashboard'
      fullPath: '/{-$locale}/dashboard'
      preLoaderRoute: typeof Char123LocaleChar125DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/briefings': {
      id: '/{-$locale}/briefings'
      path: '/{-$locale}/briefings'
      fullPath: '/{-$locale}/briefings'
      preLoaderRoute: typeof Char123LocaleChar125BriefingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/agents': {
      id: '/{-$locale}/agents'
      path: '/{-$locale}/agents'
      fullPath: '/{-$locale}/agents'
      preLoaderRoute: typeof Char123LocaleChar125AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/_views': {
      id: '/{-$locale}/_views'
      path: '/{-$locale}'
      fullPath: '/{-$locale}'
      preLoaderRoute: typeof Char123LocaleChar125ViewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/api-catalog': {
      id: '/.well-known/api-catalog'
      path: '/.well-known/api-catalog'
      fullPath: '/.well-known/api-catalog'
      preLoaderRoute: typeof DotwellKnownApiCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/sources_/$id': {
      id: '/{-$locale}/sources_/$id'
      path: '/{-$locale}/sources/$id'
      fullPath: '/{-$locale}/sources/$id'
      preLoaderRoute: typeof Char123LocaleChar125SourcesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/skills/opentrends': {
      id: '/{-$locale}/skills/opentrends'
      path: '/{-$locale}/skills/opentrends'
      fullPath: '/{-$locale}/skills/opentrends'
      preLoaderRoute: typeof Char123LocaleChar125SkillsOpentrendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/events_/flow': {
      id: '/{-$locale}/events_/flow'
      path: '/{-$locale}/events/flow'
      fullPath: '/{-$locale}/events/flow'
      preLoaderRoute: typeof Char123LocaleChar125EventsFlowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/events_/$slug': {
      id: '/{-$locale}/events_/$slug'
      path: '/{-$locale}/events/$slug'
      fullPath: '/{-$locale}/events/$slug'
      preLoaderRoute: typeof Char123LocaleChar125EventsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/_views/trends': {
      id: '/{-$locale}/_views/trends'
      path: '/trends'
      fullPath: '/{-$locale}/trends'
      preLoaderRoute: typeof Char123LocaleChar125ViewsTrendsRouteImport
      parentRoute: typeof Char123LocaleChar125ViewsRoute
    }
    '/{-$locale}/_views/feed': {
      id: '/{-$locale}/_views/feed'
      path: '/feed'
      fullPath: '/{-$locale}/feed'
      preLoaderRoute: typeof Char123LocaleChar125ViewsFeedRouteImport
      parentRoute: typeof Char123LocaleChar125ViewsRoute
    }
    '/{-$locale}/_views/events': {
      id: '/{-$locale}/_views/events'
      path: '/events'
      fullPath: '/{-$locale}/events'
      preLoaderRoute: typeof Char123LocaleChar125ViewsEventsRouteImport
      parentRoute: typeof Char123LocaleChar125ViewsRoute
    }
    '/{-$locale}/_views/calendar': {
      id: '/{-$locale}/_views/calendar'
      path: '/calendar'
      fullPath: '/{-$locale}/calendar'
      preLoaderRoute: typeof Char123LocaleChar125ViewsCalendarRouteImport
      parentRoute: typeof Char123LocaleChar125ViewsRoute
    }
    '/{-$locale}/_views/trends/': {
      id: '/{-$locale}/_views/trends/'
      path: '/'
      fullPath: '/{-$locale}/trends/'
      preLoaderRoute: typeof Char123LocaleChar125ViewsTrendsIndexRouteImport
      parentRoute: typeof Char123LocaleChar125ViewsTrendsRoute
    }
    '/{-$locale}/trends/$topic/archive': {
      id: '/{-$locale}/trends/$topic/archive'
      path: '/{-$locale}/trends/$topic/archive'
      fullPath: '/{-$locale}/trends/$topic/archive'
      preLoaderRoute: typeof Char123LocaleChar125TrendsTopicArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/trends/$topic/$day': {
      id: '/{-$locale}/trends/$topic/$day'
      path: '/{-$locale}/trends/$topic/$day'
      fullPath: '/{-$locale}/trends/$topic/$day'
      preLoaderRoute: typeof Char123LocaleChar125TrendsTopicDayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/_views/trends/$topic': {
      id: '/{-$locale}/_views/trends/$topic'
      path: '/$topic'
      fullPath: '/{-$locale}/trends/$topic'
      preLoaderRoute: typeof Char123LocaleChar125ViewsTrendsTopicRouteImport
      parentRoute: typeof Char123LocaleChar125ViewsTrendsRoute
    }
  }
}

interface Char123LocaleChar125ViewsTrendsRouteChildren {
  Char123LocaleChar125ViewsTrendsTopicRoute: typeof Char123LocaleChar125ViewsTrendsTopicRoute
  Char123LocaleChar125ViewsTrendsIndexRoute: typeof Char123LocaleChar125ViewsTrendsIndexRoute
}

const Char123LocaleChar125ViewsTrendsRouteChildren: Char123LocaleChar125ViewsTrendsRouteChildren =
  {
    Char123LocaleChar125ViewsTrendsTopicRoute:
      Char123LocaleChar125ViewsTrendsTopicRoute,
    Char123LocaleChar125ViewsTrendsIndexRoute:
      Char123LocaleChar125ViewsTrendsIndexRoute,
  }

const Char123LocaleChar125ViewsTrendsRouteWithChildren =
  Char123LocaleChar125ViewsTrendsRoute._addFileChildren(
    Char123LocaleChar125ViewsTrendsRouteChildren,
  )

interface Char123LocaleChar125ViewsRouteChildren {
  Char123LocaleChar125ViewsCalendarRoute: typeof Char123LocaleChar125ViewsCalendarRoute
  Char123LocaleChar125ViewsEventsRoute: typeof Char123LocaleChar125ViewsEventsRoute
  Char123LocaleChar125ViewsFeedRoute: typeof Char123LocaleChar125ViewsFeedRoute
  Char123LocaleChar125ViewsTrendsRoute: typeof Char123LocaleChar125ViewsTrendsRouteWithChildren
}

const Char123LocaleChar125ViewsRouteChildren: Char123LocaleChar125ViewsRouteChildren =
  {
    Char123LocaleChar125ViewsCalendarRoute:
      Char123LocaleChar125ViewsCalendarRoute,
    Char123LocaleChar125ViewsEventsRoute: Char123LocaleChar125ViewsEventsRoute,
    Char123LocaleChar125ViewsFeedRoute: Char123LocaleChar125ViewsFeedRoute,
    Char123LocaleChar125ViewsTrendsRoute:
      Char123LocaleChar125ViewsTrendsRouteWithChildren,
  }

const Char123LocaleChar125ViewsRouteWithChildren =
  Char123LocaleChar125ViewsRoute._addFileChildren(
    Char123LocaleChar125ViewsRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  PrivacyRoute: PrivacyRoute,
  SitemapArchiveDotxmlRoute: SitemapArchiveDotxmlRoute,
  SitemapEventsDotxmlRoute: SitemapEventsDotxmlRoute,
  DotwellKnownApiCatalogRoute: DotwellKnownApiCatalogRoute,
  Char123LocaleChar125ViewsRoute: Char123LocaleChar125ViewsRouteWithChildren,
  Char123LocaleChar125AgentsRoute: Char123LocaleChar125AgentsRoute,
  Char123LocaleChar125BriefingsRoute: Char123LocaleChar125BriefingsRoute,
  Char123LocaleChar125DashboardRoute: Char123LocaleChar125DashboardRoute,
  Char123LocaleChar125HistoryRoute: Char123LocaleChar125HistoryRoute,
  Char123LocaleChar125LoginRoute: Char123LocaleChar125LoginRoute,
  Char123LocaleChar125SourcesRoute: Char123LocaleChar125SourcesRoute,
  Char123LocaleChar125IndexRoute: Char123LocaleChar125IndexRoute,
  Char123LocaleChar125EventsSlugRoute: Char123LocaleChar125EventsSlugRoute,
  Char123LocaleChar125EventsFlowRoute: Char123LocaleChar125EventsFlowRoute,
  Char123LocaleChar125SkillsOpentrendsRoute:
    Char123LocaleChar125SkillsOpentrendsRoute,
  Char123LocaleChar125SourcesIdRoute: Char123LocaleChar125SourcesIdRoute,
  Char123LocaleChar125TrendsTopicDayRoute:
    Char123LocaleChar125TrendsTopicDayRoute,
  Char123LocaleChar125TrendsTopicArchiveRoute:
    Char123LocaleChar125TrendsTopicArchiveRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
