import type {
	RefreshPolicyId,
	SourceId,
	SourceKind,
	SourcePreset,
} from "../types";

const EVENT_ELIGIBLE_SOURCE_ID_LIST = [
	"9to5mac",
	"36kr-news",
	"apnews-technology",
	"appleinsider",
	"ars-technica",
	"big-think",
	"cult-of-mac",
	"engadget",
	"engadget-robotics",
	"freebuf",
	"github-blog",
	"gizmodo",
	"ifanr",
	"ieee-biomedical",
	"ieee-robotics",
	"infoq",
	"liliputing",
	"macrumors",
	"mit-tech-review",
	"mit-tech-review-ai",
	"mit-tech-review-bio",
	"new-atlas-robotics",
	"neuroscience-news",
	"quanta-magazine",
	"robot-report",
	"securityonline",
	"singularity-hub",
	"solidot",
	"sspai",
	"stackoverflow-blog",
	"techcrunch",
	"techcrunch-ai",
	"techcrunch-robotics",
	"techxplore-robotics",
	"the-decoder",
	"the-register",
	"the-verge",
	"the-verge-ai",
	"the-verge-gadgets",
	"toms-hardware",
	"venturebeat-ai",
	"wired",
	"wired-science",
] as const;

const EVENT_ELIGIBLE_SOURCE_IDS = new Set<string>(
	EVENT_ELIGIBLE_SOURCE_ID_LIST
);

function newsnowCnSource(
	name: string,
	homeUrl: string,
	refresh: RefreshPolicyId = "hot"
): SourcePreset {
	return {
		name,
		provider: "native",
		adapter: "newsnowCn",
		homeUrl,
		refresh,
	};
}

function googleNewsSource(
	name: string,
	homeUrl: string,
	query: string,
	refresh: RefreshPolicyId = "rss"
): SourcePreset {
	return {
		name,
		provider: "rss",
		homeUrl,
		feedUrl: `https://news.google.com/rss/search?q=${encodeURIComponent(query)}&hl=en-US&gl=US&ceid=US%3Aen`,
		refresh,
	};
}

export const sourcePresets = {
	// Hacker News family
	hackernews: {
		name: "Hacker News",
		provider: "native",
		adapter: "hackerNews",
		homeUrl: "https://news.ycombinator.com",
		refresh: "community",
	},
	"hackernews-best": {
		name: "Hacker News · Best",
		provider: "native",
		adapter: "hackerNews",
		homeUrl: "https://news.ycombinator.com/best",
		params: { endpoint: "best" },
		refresh: "community",
	},
	"hackernews-show": {
		name: "Show HN",
		provider: "native",
		adapter: "hackerNews",
		homeUrl: "https://news.ycombinator.com/show",
		params: { endpoint: "show" },
		refresh: "community",
	},
	"hackernews-ask": {
		name: "Ask HN",
		provider: "native",
		adapter: "hackerNews",
		homeUrl: "https://news.ycombinator.com/ask",
		params: { endpoint: "ask" },
		refresh: "community",
	},

	// Lobsters
	lobsters: {
		name: "Lobsters",
		provider: "rss",
		homeUrl: "https://lobste.rs/",
		feedUrl: "https://lobste.rs/rss",
		refresh: "rss",
	},
	"lobsters-ai": {
		name: "Lobsters · AI",
		provider: "rss",
		homeUrl: "https://lobste.rs/t/ai",
		feedUrl: "https://lobste.rs/t/ai.rss",
		refresh: "rss",
	},

	// GitHub
	"github-trending": {
		name: "GitHub Trending",
		provider: "native",
		adapter: "githubTrending",
		homeUrl: "https://github.com/trending",
		refresh: "daily",
	},
	"github-trending-weekly": {
		name: "GitHub Trending · Weekly",
		provider: "native",
		adapter: "githubTrending",
		homeUrl: "https://github.com/trending?since=weekly",
		params: { since: "weekly" },
		refresh: "daily",
	},

	// Indie / Maker
	indiehackers: {
		name: "Indie Hackers",
		provider: "rss",
		homeUrl: "https://www.indiehackers.com/",
		feedUrl: "https://www.indiehackers.com/feed.xml",
		refresh: "rss",
	},
	producthunt: {
		name: "Product Hunt",
		provider: "native",
		adapter: "productHunt",
		homeUrl: "https://www.producthunt.com",
		refresh: "daily",
	},

	// General tech press / community
	slashdot: {
		name: "Slashdot",
		provider: "rss",
		homeUrl: "https://slashdot.org/",
		feedUrl: "https://rss.slashdot.org/Slashdot/slashdotMain",
		refresh: "rss",
	},
	"the-register": {
		name: "The Register",
		provider: "rss",
		homeUrl: "https://www.theregister.com/",
		feedUrl: "https://www.theregister.com/headlines.atom",
		refresh: "rss",
	},
	"github-blog": {
		name: "GitHub Blog",
		provider: "rss",
		homeUrl: "https://github.blog/",
		feedUrl: "https://github.blog/feed/",
		refresh: "rss",
	},
	lwn: {
		name: "LWN.net",
		provider: "rss",
		homeUrl: "https://lwn.net/",
		feedUrl: "https://lwn.net/headlines/rss",
		refresh: "rss",
	},
	phoronix: {
		name: "Phoronix",
		provider: "rss",
		homeUrl: "https://www.phoronix.com/",
		feedUrl: "https://www.phoronix.com/rss.php",
		refresh: "rss",
	},

	// Mainstream tech press
	techcrunch: {
		name: "TechCrunch",
		provider: "rss",
		homeUrl: "https://techcrunch.com/",
		feedUrl: "https://techcrunch.com/feed/",
		refresh: "rss",
	},
	"techcrunch-ai": {
		name: "TechCrunch · AI",
		provider: "rss",
		homeUrl: "https://techcrunch.com/category/artificial-intelligence/",
		feedUrl: "https://techcrunch.com/category/artificial-intelligence/feed/",
		refresh: "rss",
	},
	"the-verge": {
		name: "The Verge",
		provider: "rss",
		homeUrl: "https://www.theverge.com/",
		feedUrl: "https://www.theverge.com/rss/index.xml",
		refresh: "rss",
	},
	"the-verge-ai": {
		name: "The Verge · AI",
		provider: "rss",
		homeUrl: "https://www.theverge.com/ai-artificial-intelligence",
		feedUrl:
			"https://www.theverge.com/rss/ai-artificial-intelligence/index.xml",
		refresh: "rss",
	},
	"venturebeat-ai": {
		name: "VentureBeat · AI",
		provider: "rss",
		homeUrl: "https://venturebeat.com/category/ai/",
		feedUrl: "https://venturebeat.com/category/ai/feed/",
		refresh: "rss",
	},
	"ars-technica": {
		name: "Ars Technica",
		provider: "rss",
		homeUrl: "https://arstechnica.com/",
		feedUrl: "https://feeds.arstechnica.com/arstechnica/index",
		refresh: "rss",
	},
	wired: {
		name: "Wired",
		provider: "rss",
		homeUrl: "https://www.wired.com/",
		feedUrl: "https://www.wired.com/feed/rss",
		refresh: "rss",
	},
	"wired-science": {
		name: "Wired · Science",
		provider: "rss",
		homeUrl: "https://www.wired.com/category/science/",
		feedUrl: "https://www.wired.com/feed/category/science/latest/rss",
		refresh: "rss",
	},
	engadget: {
		name: "Engadget",
		provider: "rss",
		homeUrl: "https://www.engadget.com/",
		feedUrl: "https://www.engadget.com/rss.xml",
		refresh: "rss",
	},
	"apnews-technology": {
		name: "AP News · Technology",
		provider: "rsshub",
		homeUrl: "https://apnews.com/hub/technology",
		route: "/apnews/rss/technology",
		refresh: "rss",
	},
	"mit-tech-review": {
		name: "MIT Technology Review",
		provider: "rss",
		homeUrl: "https://www.technologyreview.com/",
		feedUrl: "https://www.technologyreview.com/feed/",
		refresh: "rss",
	},
	"mit-tech-review-ai": {
		name: "MIT Tech Review · AI",
		provider: "rss",
		homeUrl: "https://www.technologyreview.com/topic/artificial-intelligence/",
		feedUrl:
			"https://www.technologyreview.com/topic/artificial-intelligence/feed",
		refresh: "rss",
	},
	"quanta-magazine": {
		name: "Quanta Magazine",
		provider: "rss",
		homeUrl: "https://www.quantamagazine.org/",
		feedUrl: "https://www.quantamagazine.org/feed/",
		refresh: "rss",
	},
	"big-think": {
		name: "Big Think",
		provider: "rss",
		homeUrl: "https://bigthink.com/",
		feedUrl: "https://bigthink.com/feed/",
		refresh: "rss",
	},
	nature: {
		name: "Nature",
		provider: "rss",
		homeUrl: "https://www.nature.com/nature/",
		feedUrl: "https://www.nature.com/nature.rss",
		refresh: "rss",
	},
	"phys-org": {
		name: "Phys.org",
		provider: "rss",
		homeUrl: "https://phys.org/",
		feedUrl: "https://phys.org/rss-feed/",
		refresh: "rss",
	},
	"singularity-hub": {
		name: "Singularity Hub",
		provider: "rss",
		homeUrl: "https://singularityhub.com/",
		feedUrl: "https://singularityhub.com/feed/",
		refresh: "rss",
	},
	"daring-fireball": {
		name: "Daring Fireball",
		provider: "rss",
		homeUrl: "https://daringfireball.net/",
		feedUrl: "https://daringfireball.net/feeds/main",
		refresh: "rss",
	},
	appleinsider: {
		name: "AppleInsider",
		provider: "rss",
		homeUrl: "https://appleinsider.com/",
		feedUrl: "https://appleinsider.com/rss/news/",
		refresh: "rss",
	},
	"cult-of-mac": {
		name: "Cult of Mac",
		provider: "rss",
		homeUrl: "https://www.cultofmac.com/",
		feedUrl: "https://www.cultofmac.com/feed/",
		refresh: "rss",
	},
	macrumors: {
		name: "MacRumors",
		provider: "rss",
		homeUrl: "https://www.macrumors.com/",
		feedUrl: "https://feeds.macrumors.com/MacRumors-All",
		refresh: "rss",
	},
	"9to5mac": {
		name: "9to5Mac",
		provider: "rsshub",
		homeUrl: "https://9to5mac.com/",
		route: "/9to5/9to5mac",
		refresh: "rss",
	},
	securityonline: {
		name: "SecurityOnline",
		provider: "rss",
		homeUrl: "https://securityonline.info/",
		feedUrl: "https://securityonline.info/feed/",
		refresh: "rss",
	},
	"coindesk-news": {
		name: "CoinDesk",
		provider: "rsshub",
		homeUrl: "https://www.coindesk.com/",
		route: "/coindesk/news",
		refresh: "rss",
	},
	cointelegraph: {
		name: "Cointelegraph",
		provider: "rsshub",
		homeUrl: "https://cointelegraph.com/",
		route: "/cointelegraph",
		refresh: "rss",
	},

	// Global news / business press
	economist: {
		name: "The Economist",
		provider: "rss",
		homeUrl: "https://www.economist.com/",
		feedUrl: "https://www.economist.com/latest/rss.xml",
		refresh: "rss",
	},
	bloomberg: {
		name: "Bloomberg",
		provider: "rss",
		homeUrl: "https://www.bloomberg.com/",
		feedUrl:
			"https://news.google.com/rss/search?q=site%3Abloomberg.com&hl=en-US&gl=US&ceid=US%3Aen",
		refresh: "rss",
	},
	"the-atlantic": {
		name: "The Atlantic",
		provider: "rss",
		homeUrl: "https://www.theatlantic.com/",
		feedUrl: "https://www.theatlantic.com/feed/all/",
		refresh: "rss",
	},
	"bbc-news": {
		name: "BBC News",
		provider: "rss",
		homeUrl: "https://www.bbc.com/news",
		feedUrl: "https://feeds.bbci.co.uk/news/rss.xml",
		refresh: "rss",
	},
	nytimes: {
		name: "The New York Times",
		provider: "rss",
		homeUrl: "https://www.nytimes.com/",
		feedUrl: "https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml",
		refresh: "rss",
	},
	"yahoo-finance": {
		name: "Yahoo Finance",
		provider: "rss",
		homeUrl: "https://finance.yahoo.com/",
		feedUrl: "https://finance.yahoo.com/news/rssindex",
		refresh: "rss",
	},
	"the-guardian": {
		name: "The Guardian",
		provider: "rss",
		homeUrl: "https://www.theguardian.com/international",
		feedUrl: "https://www.theguardian.com/international/rss",
		refresh: "rss",
	},
	"financial-times": {
		name: "Financial Times",
		provider: "rss",
		homeUrl: "https://www.ft.com/",
		feedUrl: "https://www.ft.com/rss/home",
		refresh: "rss",
	},
	wsj: {
		name: "The Wall Street Journal",
		provider: "rss",
		homeUrl: "https://www.wsj.com/",
		feedUrl: "https://feeds.a.dj.com/rss/RSSWorldNews.xml",
		refresh: "rss",
	},
	reuters: {
		name: "Reuters",
		provider: "rss",
		homeUrl: "https://www.reuters.com/",
		feedUrl:
			"https://news.google.com/rss/search?q=site%3Areuters.com&hl=en-US&gl=US&ceid=US%3Aen",
		refresh: "rss",
	},
	axios: {
		name: "Axios",
		provider: "rss",
		homeUrl: "https://www.axios.com/",
		feedUrl: "https://www.axios.com/feeds/feed.rss",
		refresh: "rss",
	},
	"business-insider": {
		name: "Business Insider",
		provider: "rss",
		homeUrl: "https://www.businessinsider.com/",
		feedUrl: "https://www.businessinsider.com/rss",
		refresh: "rss",
	},
	"sky-news": {
		name: "Sky News",
		provider: "rss",
		homeUrl: "https://news.sky.com/",
		feedUrl: "https://feeds.skynews.com/feeds/rss/home.xml",
		refresh: "rss",
	},
	"google-news": {
		name: "Google News",
		provider: "rss",
		homeUrl: "https://news.google.com/",
		feedUrl: "https://news.google.com/rss?hl=en-US&gl=US&ceid=US:en",
		refresh: "rss",
	},
	politico: {
		name: "Politico",
		provider: "rss",
		homeUrl: "https://www.politico.com/",
		feedUrl: "https://rss.politico.com/politics-news.xml",
		refresh: "rss",
	},
	"new-yorker": {
		name: "The New Yorker",
		provider: "rss",
		homeUrl: "https://www.newyorker.com/",
		feedUrl: "https://www.newyorker.com/feed/everything",
		refresh: "rss",
	},

	// Developer-leaning publications
	"daily-dev-popular": {
		name: "daily.dev · Popular",
		provider: "rsshub",
		homeUrl: "https://app.daily.dev/",
		route: "/daily/popular",
		refresh: "community",
	},
	devto: {
		name: "DEV.to",
		provider: "rss",
		homeUrl: "https://dev.to/",
		feedUrl: "https://dev.to/feed",
		refresh: "rss",
	},
	"smashing-mag": {
		name: "Smashing Magazine",
		provider: "rss",
		homeUrl: "https://www.smashingmagazine.com/",
		feedUrl: "https://www.smashingmagazine.com/feed/",
		refresh: "rss",
	},
	"css-tricks": {
		name: "CSS-Tricks",
		provider: "rss",
		homeUrl: "https://css-tricks.com/",
		feedUrl: "https://css-tricks.com/feed/",
		refresh: "rss",
	},
	infoq: {
		name: "InfoQ",
		provider: "rss",
		homeUrl: "https://www.infoq.com/",
		feedUrl: "https://feed.infoq.com/",
		refresh: "rss",
	},
	"stackoverflow-blog": {
		name: "Stack Overflow Blog",
		provider: "rss",
		homeUrl: "https://stackoverflow.blog/",
		feedUrl: "https://stackoverflow.blog/feed/",
		refresh: "rss",
	},
	freecodecamp: {
		name: "freeCodeCamp",
		provider: "rss",
		homeUrl: "https://www.freecodecamp.org/news/",
		feedUrl: "https://www.freecodecamp.org/news/rss/",
		refresh: "rss",
	},
	// AI vendor blogs / research
	"huggingface-blog": {
		name: "Hugging Face Blog",
		provider: "rss",
		homeUrl: "https://huggingface.co/blog",
		feedUrl: "https://huggingface.co/blog/feed.xml",
		refresh: "rss",
	},
	"huggingface-papers": {
		name: "Hugging Face · Daily Papers",
		provider: "rsshub",
		homeUrl: "https://huggingface.co/papers",
		route: "/huggingface/daily-papers",
		refresh: "slow",
	},
	"openai-news": {
		name: "OpenAI News",
		provider: "rss",
		homeUrl: "https://openai.com/news",
		feedUrl: "https://openai.com/news/rss.xml",
		refresh: "rss",
	},
	"openai-research": {
		name: "OpenAI Research",
		provider: "rsshub",
		homeUrl: "https://openai.com/research/",
		route: "/openai/research",
		refresh: "rss",
	},
	"openai-cookbook": {
		name: "OpenAI Cookbook",
		provider: "rsshub",
		homeUrl: "https://cookbook.openai.com/",
		route: "/openai/cookbook",
		refresh: "rss",
	},
	"openai-alignment": googleNewsSource(
		"OpenAI Alignment",
		"https://alignment.openai.com/",
		"site:alignment.openai.com"
	),
	"openai-academy": googleNewsSource(
		"OpenAI Academy",
		"https://openai.com/academy/",
		"site:openai.com/academy OpenAI Academy"
	),
	"anthropic-news": {
		name: "Anthropic News",
		provider: "rsshub",
		homeUrl: "https://www.anthropic.com/news",
		route: "/anthropic/news",
		refresh: "rss",
	},
	"anthropic-research": {
		name: "Anthropic Research",
		provider: "rsshub",
		homeUrl: "https://www.anthropic.com/research",
		route: "/anthropic/research",
		refresh: "rss",
	},
	"anthropic-engineering": {
		name: "Anthropic Engineering",
		provider: "rsshub",
		homeUrl: "https://www.anthropic.com/engineering",
		route: "/anthropic/engineering",
		refresh: "rss",
	},
	"transformer-circuits": googleNewsSource(
		"Transformer Circuits",
		"https://transformer-circuits.pub/",
		"site:transformer-circuits.pub"
	),
	"claude-blog": googleNewsSource(
		"Claude Blog",
		"https://claude.com/blog",
		"site:claude.com/blog Claude"
	),
	"claude-code-releases": {
		name: "Claude Code Releases",
		provider: "rss",
		homeUrl: "https://github.com/anthropics/claude-code/releases",
		feedUrl: "https://github.com/anthropics/claude-code/releases.atom",
		refresh: "rss",
	},
	"xai-news": googleNewsSource(
		"xAI News",
		"https://x.ai/news",
		"site:x.ai/news"
	),
	"qwen-research": {
		name: "Qwen Research",
		provider: "native",
		adapter: "qwenResearch",
		homeUrl: "https://qwen.ai/research",
		refresh: "rss",
	},
	"qwen-blog": googleNewsSource(
		"Qwen Blog",
		"https://qwenlm.github.io/",
		"site:qwenlm.github.io Qwen"
	),
	"zhipu-research": googleNewsSource(
		"Zhipu AI Research",
		"https://www.zhipu.ai/",
		"Zhipu AI research model"
	),
	"bytedance-seed": googleNewsSource(
		"ByteDance Seed Research",
		"https://seed.bytedance.com/zh/",
		"site:seed.bytedance.com"
	),
	"tencent-hunyuan": googleNewsSource(
		"Tencent Hunyuan Research",
		"https://hunyuan.tencent.com/",
		"site:hunyuan.tencent.com"
	),
	"inclusionai-huggingface": googleNewsSource(
		"inclusionAI",
		"https://huggingface.co/inclusionAI",
		"site:huggingface.co/inclusionAI"
	),
	"ant-bailing-blog": googleNewsSource(
		"Ant Bailing Developer Blog",
		"https://ling-ai.antgroup.com/",
		"Ant Bailing large model ling-ai"
	),
	"meituan-longcat": googleNewsSource(
		"Meituan LongCat",
		"https://huggingface.co/meituan",
		"site:huggingface.co/meituan LongCat"
	),
	"kimi-updates": googleNewsSource(
		"Moonshot AI Kimi",
		"https://kimi.moonshot.cn/",
		// kimi.com itself only yields product pages with one shared title, so
		// this follows the coverage instead.
		'"Moonshot AI" OR "Kimi K"'
	),
	"minimax-news": googleNewsSource(
		"MiniMax",
		"https://www.minimaxi.com/",
		"site:minimaxi.com MiniMax"
	),
	"latent-space": {
		name: "Latent Space",
		provider: "rss",
		homeUrl: "https://www.latent.space/",
		feedUrl: "https://www.latent.space/feed",
		refresh: "rss",
	},
	"simon-willison": {
		name: "Simon Willison",
		provider: "rss",
		homeUrl: "https://simonwillison.net/",
		feedUrl: "https://simonwillison.net/atom/everything/",
		refresh: "rss",
	},
	"sebastian-raschka": {
		name: "Ahead of AI",
		provider: "rss",
		homeUrl: "https://magazine.sebastianraschka.com/",
		feedUrl: "https://magazine.sebastianraschka.com/feed",
		refresh: "rss",
	},
	"mozilla-ai": {
		name: "Mozilla.ai Blog",
		provider: "rss",
		homeUrl: "https://blog.mozilla.ai/",
		feedUrl: "https://blog.mozilla.ai/rss/",
		refresh: "rss",
	},
	"google-research-blog": {
		name: "Google Research Blog",
		provider: "rss",
		homeUrl: "https://research.google/blog/",
		feedUrl: "https://research.google/blog/rss/",
		refresh: "rss",
	},
	"google-ai-blog": {
		name: "Google AI Blog",
		provider: "rss",
		homeUrl: "https://blog.google/technology/ai/",
		feedUrl: "https://blog.google/technology/ai/rss/",
		refresh: "rss",
	},
	"google-developers-blog": {
		name: "Google Developers Blog",
		provider: "rss",
		homeUrl: "https://developers.googleblog.com/",
		feedUrl: "https://developers.googleblog.com/feeds/posts/default?alt=rss",
		refresh: "rss",
	},
	"deepmind-blog": {
		name: "Google DeepMind Blog",
		provider: "rsshub",
		homeUrl: "https://deepmind.google/discover/blog/",
		route: "/deepmind/blog",
		refresh: "rss",
	},
	"apple-ml-research": {
		name: "Apple Machine Learning Research",
		provider: "rss",
		homeUrl: "https://machinelearning.apple.com/",
		feedUrl: "https://machinelearning.apple.com/rss.xml",
		refresh: "rss",
	},
	"apple-newsroom": {
		name: "Apple Newsroom",
		provider: "rss",
		homeUrl: "https://www.apple.com/newsroom/",
		feedUrl: "https://www.apple.com/newsroom/rss-feed.rss",
		refresh: "rss",
	},
	"meta-ai-blog": googleNewsSource(
		"Meta AI Blog",
		"https://ai.meta.com/blog/",
		"site:ai.meta.com/blog"
	),
	"meta-engineering": {
		name: "Meta Engineering",
		provider: "rss",
		homeUrl: "https://engineering.fb.com/",
		feedUrl: "https://engineering.fb.com/feed/",
		refresh: "rss",
	},
	"nvidia-ai-blog": googleNewsSource(
		"NVIDIA AI Blog",
		"https://blogs.nvidia.com/ai/",
		"site:blogs.nvidia.com/ai OR site:blogs.nvidia.com/blog/tag/ai"
	),
	"cloudflare-blog": {
		name: "Cloudflare Blog",
		provider: "rss",
		homeUrl: "https://blog.cloudflare.com/",
		feedUrl: "https://blog.cloudflare.com/rss/",
		refresh: "rss",
	},
	"cursor-blog": googleNewsSource(
		"Cursor Blog",
		"https://www.cursor.com/blog",
		"site:cursor.com/blog Cursor"
	),
	"runway-news": googleNewsSource(
		"Runway News",
		"https://runway.com/news/",
		"site:runway.com/news Runway"
	),
	"runway-changelog": googleNewsSource(
		"Runway Changelog",
		"https://runway.com/changelog/",
		"site:runway.com/changelog Runway"
	),
	"midjourney-updates": googleNewsSource(
		"Midjourney Updates",
		"https://www.midjourney.com/updates",
		"site:midjourney.com/updates Midjourney"
	),
	"suno-blog": googleNewsSource(
		"Suno Blog",
		"https://suno.com/blog/",
		"site:suno.com/blog Suno"
	),
	"openrouter-announcements": googleNewsSource(
		"OpenRouter Announcements",
		"https://openrouter.ai/blog/announcements/",
		"site:openrouter.ai/blog/announcements OpenRouter"
	),
	"lmsys-blog": googleNewsSource(
		"LMSYS Blog",
		"https://lmsys.org/blog/",
		"site:lmsys.org/blog"
	),
	"eleutherai-blog": googleNewsSource(
		"EleutherAI Blog",
		"https://blog.eleuther.ai/",
		"site:blog.eleuther.ai"
	),
	"berkeley-rdi": googleNewsSource(
		"Berkeley RDI",
		"https://rdi.berkeley.edu/",
		"site:rdi.berkeley.edu"
	),
	"cmu-ml-blog": {
		name: "CMU Machine Learning Blog",
		provider: "rss",
		homeUrl: "https://blog.ml.cmu.edu/",
		feedUrl: "https://blog.ml.cmu.edu/feed/",
		refresh: "rss",
	},
	"gary-marcus": {
		name: "Gary Marcus",
		provider: "rss",
		homeUrl: "https://garymarcus.substack.com/",
		feedUrl: "https://garymarcus.substack.com/feed",
		refresh: "rss",
	},
	"tomer-tunguz": {
		name: "Tomer Tunguz",
		provider: "rss",
		homeUrl: "https://tomtunguz.com/",
		feedUrl: "https://tomtunguz.com/index.xml",
		refresh: "rss",
	},
	interconnects: {
		name: "Interconnects",
		provider: "rss",
		homeUrl: "https://www.interconnects.ai/",
		feedUrl: "https://www.interconnects.ai/feed",
		refresh: "rss",
	},
	"dwarkesh-patel": {
		name: "Dwarkesh Patel",
		provider: "rss",
		homeUrl: "https://www.dwarkesh.com/",
		feedUrl: "https://www.dwarkesh.com/feed",
		refresh: "rss",
	},
	"one-useful-thing": {
		name: "One Useful Thing",
		provider: "rss",
		homeUrl: "https://www.oneusefulthing.org/",
		feedUrl: "https://www.oneusefulthing.org/feed",
		refresh: "rss",
	},
	"dario-amodei": googleNewsSource(
		"Dario Amodei",
		"https://darioamodei.com/",
		"site:darioamodei.com Dario Amodei"
	),
	"sam-altman": {
		name: "Sam Altman",
		provider: "rss",
		homeUrl: "https://blog.samaltman.com/",
		feedUrl: "https://blog.samaltman.com/posts.atom",
		refresh: "rss",
	},
	"deepseek-github": googleNewsSource(
		"DeepSeek GitHub",
		"https://github.com/deepseek-ai/",
		"DeepSeek GitHub release repository"
	),
	"descript-blog": googleNewsSource(
		"Descript Blog",
		"https://www.descript.com/blog",
		"site:descript.com/blog Descript"
	),
	"servicenow-ai": googleNewsSource(
		"ServiceNow AI",
		"https://www.servicenow.com/blogs.html",
		"site:servicenow.com/blogs AI ServiceNow"
	),
	"deeplearning-the-batch": {
		name: "DeepLearning.AI · The Batch",
		provider: "rsshub",
		homeUrl: "https://www.deeplearning.ai/the-batch/",
		route: "/deeplearning/the-batch",
		refresh: "rss",
	},
	"arxiv-cs-ai": {
		name: "arXiv · cs.AI",
		provider: "rss",
		homeUrl: "https://arxiv.org/list/cs.AI/recent",
		feedUrl: "https://export.arxiv.org/rss/cs.AI",
		refresh: "slow",
	},
	"arxiv-cs-lg": {
		name: "arXiv · cs.LG",
		provider: "rss",
		homeUrl: "https://arxiv.org/list/cs.LG/recent",
		feedUrl: "https://export.arxiv.org/rss/cs.LG",
		refresh: "slow",
	},
	"arxiv-cs-cl": {
		name: "arXiv · cs.CL",
		provider: "rss",
		homeUrl: "https://arxiv.org/list/cs.CL/recent",
		feedUrl: "https://export.arxiv.org/rss/cs.CL",
		refresh: "slow",
	},
	"bair-blog": {
		name: "Berkeley AI Research",
		provider: "rss",
		homeUrl: "https://bair.berkeley.edu/blog/",
		feedUrl: "https://bair.berkeley.edu/blog/feed.xml",
		refresh: "rss",
	},
	"the-gradient": {
		name: "The Gradient",
		provider: "rss",
		homeUrl: "https://thegradient.pub/",
		feedUrl: "https://thegradient.pub/rss/",
		refresh: "rss",
	},
	"the-decoder": {
		name: "The Decoder",
		provider: "rss",
		homeUrl: "https://the-decoder.com/",
		feedUrl: "https://the-decoder.com/feed/",
		refresh: "rss",
	},
	"karpathy-blog": {
		name: "Andrej Karpathy",
		provider: "rss",
		homeUrl: "https://karpathy.github.io/",
		feedUrl: "https://karpathy.github.io/feed.xml",
		refresh: "slow",
	},
	"lilian-weng": {
		name: "Lil'Log (Lilian Weng)",
		provider: "rss",
		homeUrl: "https://lilianweng.github.io/",
		feedUrl: "https://lilianweng.github.io/index.xml",
		refresh: "slow",
	},

	// Reddit
	"reddit-programming": {
		name: "r/programming",
		provider: "native",
		adapter: "reddit",
		homeUrl: "https://www.reddit.com/r/programming/",
		params: { subreddit: "programming" },
		refresh: "community",
	},
	"reddit-webdev": {
		name: "r/webdev",
		provider: "native",
		adapter: "reddit",
		homeUrl: "https://www.reddit.com/r/webdev/",
		params: { subreddit: "webdev" },
		refresh: "community",
	},
	"reddit-rust": {
		name: "r/rust",
		provider: "native",
		adapter: "reddit",
		homeUrl: "https://www.reddit.com/r/rust/",
		params: { subreddit: "rust" },
		refresh: "community",
	},
	"reddit-golang": {
		name: "r/golang",
		provider: "native",
		adapter: "reddit",
		homeUrl: "https://www.reddit.com/r/golang/",
		params: { subreddit: "golang" },
		refresh: "community",
	},
	"reddit-startups": {
		name: "r/startups",
		provider: "native",
		adapter: "reddit",
		homeUrl: "https://www.reddit.com/r/startups/",
		params: { subreddit: "startups" },
		refresh: "community",
	},
	"reddit-saas": {
		name: "r/SaaS",
		provider: "native",
		adapter: "reddit",
		homeUrl: "https://www.reddit.com/r/SaaS/",
		params: { subreddit: "SaaS" },
		refresh: "community",
	},
	"reddit-entrepreneur": {
		name: "r/Entrepreneur",
		provider: "native",
		adapter: "reddit",
		homeUrl: "https://www.reddit.com/r/Entrepreneur/",
		params: { subreddit: "Entrepreneur" },
		refresh: "community",
	},
	"reddit-machinelearning": {
		name: "r/MachineLearning",
		provider: "native",
		adapter: "reddit",
		homeUrl: "https://www.reddit.com/r/MachineLearning/",
		params: { subreddit: "MachineLearning" },
		refresh: "community",
	},
	"reddit-localllama": {
		name: "r/LocalLLaMA",
		provider: "native",
		adapter: "reddit",
		homeUrl: "https://www.reddit.com/r/LocalLLaMA/",
		params: { subreddit: "LocalLLaMA" },
		refresh: "community",
	},
	"reddit-reinforcementlearning": {
		name: "r/reinforcementlearning",
		provider: "native",
		adapter: "reddit",
		homeUrl: "https://www.reddit.com/r/reinforcementlearning/",
		params: { subreddit: "reinforcementlearning" },
		refresh: "community",
	},
	"reddit-sideproject": {
		name: "r/SideProject",
		provider: "native",
		adapter: "reddit",
		homeUrl: "https://www.reddit.com/r/SideProject/",
		params: { subreddit: "SideProject" },
		refresh: "community",
	},
	"reddit-indiehackers": {
		name: "r/indiehackers",
		provider: "native",
		adapter: "reddit",
		homeUrl: "https://www.reddit.com/r/indiehackers/",
		params: { subreddit: "indiehackers" },
		refresh: "community",
	},
	"reddit-microsaas": {
		name: "r/microsaas",
		provider: "native",
		adapter: "reddit",
		homeUrl: "https://www.reddit.com/r/microsaas/",
		params: { subreddit: "microsaas" },
		refresh: "community",
	},

	// Embodied AI / Robotics
	"arxiv-robotics": {
		name: "arXiv · cs.RO",
		provider: "rss",
		homeUrl: "https://arxiv.org/list/cs.RO/recent",
		feedUrl: "https://export.arxiv.org/rss/cs.RO",
		refresh: "slow",
	},
	"ieee-robotics": {
		name: "IEEE Spectrum Robotics",
		provider: "rss",
		homeUrl: "https://spectrum.ieee.org/robotics",
		feedUrl: "https://spectrum.ieee.org/feeds/topic/robotics.rss",
		refresh: "rss",
	},
	"techcrunch-robotics": {
		name: "TechCrunch · Robotics",
		provider: "rss",
		homeUrl: "https://techcrunch.com/category/robotics/",
		feedUrl: "https://techcrunch.com/category/robotics/feed/",
		refresh: "rss",
	},
	"new-atlas-robotics": {
		name: "New Atlas · Robotics",
		provider: "rss",
		homeUrl: "https://newatlas.com/robotics/",
		feedUrl: "https://newatlas.com/robotics/index.rss",
		refresh: "rss",
	},
	"engadget-robotics": {
		name: "Engadget · Robotics",
		provider: "rss",
		homeUrl: "https://www.engadget.com/science/robotics/",
		feedUrl: "https://www.engadget.com/category/robotics/feed/",
		refresh: "rss",
	},
	"techxplore-robotics": {
		name: "Tech Xplore · Robotics",
		provider: "rss",
		homeUrl: "https://techxplore.com/robotics-news/",
		feedUrl: "https://techxplore.com/rss-feed/robotics-news/",
		refresh: "rss",
	},
	"qbitai-embodied": {
		name: "量子位 · 具身智能",
		provider: "rsshub",
		homeUrl: "https://www.qbitai.com/tag/%E5%85%B7%E8%BA%AB%E6%99%BA%E8%83%BD",
		route: "/qbitai/tag/具身智能",
		refresh: "rss",
	},
	"robot-report": {
		name: "The Robot Report",
		provider: "rss",
		homeUrl: "https://www.therobotreport.com/",
		feedUrl: "https://www.therobotreport.com/feed/",
		refresh: "rss",
	},
	robohub: {
		name: "Robohub",
		provider: "rss",
		homeUrl: "https://robohub.org/",
		feedUrl: "https://robohub.org/feed/",
		refresh: "rss",
	},
	"boston-dynamics": {
		name: "Boston Dynamics Blog",
		provider: "rss",
		homeUrl: "https://blog.bostondynamics.com/",
		feedUrl: "https://blog.bostondynamics.com/rss.xml",
		refresh: "rss",
	},
	"nvidia-news-robotics": {
		name: "NVIDIA Blog · Robotics",
		provider: "rss",
		homeUrl: "https://blogs.nvidia.com/blog/tag/robotics/",
		feedUrl: "https://blogs.nvidia.com/blog/tag/robotics/feed/",
		refresh: "rss",
	},
	"nvidia-dev-robotics": {
		name: "NVIDIA Technical Blog · Robotics",
		provider: "rss",
		homeUrl: "https://developer.nvidia.com/blog/category/robotics/",
		feedUrl: "https://developer.nvidia.com/blog/category/robotics/feed/",
		refresh: "rss",
	},
	"mit-news-robotics": {
		name: "MIT News · Robotics",
		provider: "rss",
		homeUrl: "https://news.mit.edu/topic/robotics",
		feedUrl: "https://news.mit.edu/topic/mitrobotics-rss.xml",
		refresh: "rss",
	},
	"open-robotics-blog": {
		name: "Open Robotics Blog",
		provider: "rss",
		homeUrl: "https://www.openrobotics.org/blog",
		feedUrl: "https://www.openrobotics.org/blog?format=rss",
		refresh: "rss",
	},
	"robotics-automation-news": {
		name: "Robotics & Automation News",
		provider: "rss",
		homeUrl: "https://roboticsandautomationnews.com/category/robotics/",
		feedUrl: "https://roboticsandautomationnews.com/category/robotics/feed/",
		refresh: "rss",
	},
	"robotics-tomorrow": {
		name: "Robotics Tomorrow",
		provider: "rss",
		homeUrl: "https://www.roboticstomorrow.com/",
		feedUrl: "https://www.roboticstomorrow.com/rss/news/",
		refresh: "rss",
	},
	bdtechtalks: {
		name: "BD Tech Talks",
		provider: "rss",
		homeUrl: "https://bdtechtalks.com/",
		feedUrl: "https://bdtechtalks.com/feed/",
		refresh: "rss",
	},
	"synced-review": {
		name: "Synced Review",
		provider: "rss",
		homeUrl: "https://syncedreview.com/",
		feedUrl: "https://syncedreview.com/feed/",
		refresh: "rss",
	},
	"reddit-robotics": {
		name: "r/robotics",
		provider: "native",
		adapter: "reddit",
		homeUrl: "https://www.reddit.com/r/robotics/",
		params: { subreddit: "robotics" },
		refresh: "community",
	},
	"arxiv-cs-cv": {
		name: "arXiv · cs.CV",
		provider: "rss",
		homeUrl: "https://arxiv.org/list/cs.CV/recent",
		feedUrl: "https://export.arxiv.org/rss/cs.CV",
		refresh: "slow",
	},
	"arxiv-eess-sy": {
		name: "arXiv · eess.SY",
		provider: "rss",
		homeUrl: "https://arxiv.org/list/eess.SY/recent",
		feedUrl: "https://export.arxiv.org/rss/eess.SY",
		refresh: "slow",
	},
	"ros-discourse": {
		name: "ROS Discourse",
		provider: "rss",
		homeUrl: "https://discourse.ros.org/",
		feedUrl: "https://discourse.ros.org/latest.rss",
		refresh: "rss",
	},
	"planet-ros": {
		name: "Planet ROS",
		provider: "rss",
		homeUrl: "https://planet.ros.org/",
		feedUrl: "https://planet.ros.org/rss20.xml",
		refresh: "rss",
	},

	// Smart Hardware / Devices
	hackaday: {
		name: "Hackaday",
		provider: "rss",
		homeUrl: "https://hackaday.com/",
		feedUrl: "https://hackaday.com/feed/",
		refresh: "rss",
	},
	"toms-hardware": {
		name: "Tom's Hardware",
		provider: "rss",
		homeUrl: "https://www.tomshardware.com/",
		feedUrl: "https://www.tomshardware.com/feeds/all",
		refresh: "rss",
	},
	"nvidia-blog": {
		name: "NVIDIA Blog",
		provider: "rss",
		homeUrl: "https://blogs.nvidia.com/",
		feedUrl: "https://blogs.nvidia.com/feed/",
		refresh: "rss",
	},
	"the-verge-gadgets": {
		name: "The Verge · Gadgets",
		provider: "rss",
		homeUrl: "https://www.theverge.com/gadgets",
		feedUrl: "https://www.theverge.com/rss/gadgets/index.xml",
		refresh: "rss",
	},
	gizmodo: {
		name: "Gizmodo",
		provider: "rss",
		homeUrl: "https://gizmodo.com/",
		feedUrl: "https://gizmodo.com/feed/rss",
		refresh: "rss",
	},
	"kickstarter-tech": {
		name: "Kickstarter · Technology",
		provider: "native",
		adapter: "kickstarter",
		homeUrl: "https://www.kickstarter.com/discover/categories/technology",
		refresh: "daily",
	},
	crowdsupply: {
		name: "Crowd Supply",
		provider: "native",
		adapter: "crowdSupply",
		homeUrl: "https://www.crowdsupply.com/",
		refresh: "daily",
	},
	"reddit-hardware": {
		name: "r/hardware",
		provider: "native",
		adapter: "reddit",
		homeUrl: "https://www.reddit.com/r/hardware/",
		params: { subreddit: "hardware" },
		refresh: "community",
	},
	"reddit-gadgets": {
		name: "r/gadgets",
		provider: "native",
		adapter: "reddit",
		homeUrl: "https://www.reddit.com/r/gadgets/",
		params: { subreddit: "gadgets" },
		refresh: "community",
	},
	"reddit-embedded": {
		name: "r/embedded",
		provider: "native",
		adapter: "reddit",
		homeUrl: "https://www.reddit.com/r/embedded/",
		params: { subreddit: "embedded" },
		refresh: "community",
	},
	"reddit-raspberrypi": {
		name: "r/raspberry_pi",
		provider: "native",
		adapter: "reddit",
		homeUrl: "https://www.reddit.com/r/raspberry_pi/",
		params: { subreddit: "raspberry_pi" },
		refresh: "community",
	},
	"serve-the-home": {
		name: "ServeTheHome",
		provider: "rss",
		homeUrl: "https://www.servethehome.com/",
		feedUrl: "https://www.servethehome.com/feed/",
		refresh: "rss",
	},
	adafruit: {
		name: "Adafruit Blog",
		provider: "rss",
		homeUrl: "https://blog.adafruit.com/",
		feedUrl: "https://blog.adafruit.com/feed/",
		refresh: "rss",
	},
	"make-magazine": {
		name: "Make: Magazine",
		provider: "rss",
		homeUrl: "https://makezine.com/",
		feedUrl: "https://makezine.com/feed/",
		refresh: "rss",
	},
	"tindie-blog": {
		name: "Tindie Blog",
		provider: "rss",
		homeUrl: "https://blog.tindie.com/",
		feedUrl: "https://blog.tindie.com/feed/",
		refresh: "rss",
	},
	liliputing: {
		name: "Liliputing",
		provider: "rss",
		homeUrl: "https://liliputing.com/",
		feedUrl: "https://liliputing.com/feed",
		refresh: "rss",
	},

	// Brain-Computer Interface / Neurotech
	"nature-bmi": {
		name: "Nature · Brain–machine interface",
		provider: "rss",
		homeUrl: "https://www.nature.com/subjects/brain-machine-interface",
		feedUrl: "https://www.nature.com/subjects/brain-machine-interface.rss",
		refresh: "slow",
	},
	"nature-neuroscience": {
		name: "Nature Neuroscience",
		provider: "rss",
		homeUrl: "https://www.nature.com/neuro/",
		feedUrl: "https://www.nature.com/neuro.rss",
		refresh: "slow",
	},
	"arxiv-q-bio-nc": {
		name: "arXiv · q-bio.NC",
		provider: "rss",
		homeUrl: "https://arxiv.org/list/q-bio.NC/recent",
		feedUrl: "https://export.arxiv.org/rss/q-bio.NC",
		refresh: "slow",
	},
	"frontiers-neuroscience": {
		name: "Frontiers in Neuroscience",
		provider: "rss",
		homeUrl: "https://www.frontiersin.org/journals/neuroscience",
		feedUrl: "https://www.frontiersin.org/journals/neuroscience/rss",
		refresh: "rss",
	},
	"ieee-biomedical": {
		name: "IEEE Spectrum Biomedical",
		provider: "rss",
		homeUrl: "https://spectrum.ieee.org/biomedical",
		feedUrl: "https://spectrum.ieee.org/feeds/topic/biomedical.rss",
		refresh: "rss",
	},
	"mit-tech-review-bio": {
		name: "MIT Tech Review · Biotech",
		provider: "rss",
		homeUrl: "https://www.technologyreview.com/topic/biotechnology/",
		feedUrl: "https://www.technologyreview.com/topic/biotechnology/feed",
		refresh: "rss",
	},
	"reddit-neuralink": {
		name: "r/Neuralink",
		provider: "native",
		adapter: "reddit",
		homeUrl: "https://www.reddit.com/r/Neuralink/",
		params: { subreddit: "Neuralink" },
		refresh: "community",
	},
	"reddit-bci": {
		name: "r/BCI",
		provider: "native",
		adapter: "reddit",
		homeUrl: "https://www.reddit.com/r/BCI/",
		params: { subreddit: "BCI" },
		refresh: "community",
	},
	"reddit-neuroscience": {
		name: "r/neuroscience",
		provider: "native",
		adapter: "reddit",
		homeUrl: "https://www.reddit.com/r/neuroscience/",
		params: { subreddit: "neuroscience" },
		refresh: "community",
	},
	"reddit-neuroengineering": {
		name: "r/neuroengineering",
		provider: "native",
		adapter: "reddit",
		homeUrl: "https://www.reddit.com/r/neuroengineering/",
		params: { subreddit: "neuroengineering" },
		refresh: "community",
	},
	"arxiv-cs-ne": {
		name: "arXiv · cs.NE",
		provider: "rss",
		homeUrl: "https://arxiv.org/list/cs.NE/recent",
		feedUrl: "https://export.arxiv.org/rss/cs.NE",
		refresh: "slow",
	},
	"frontiers-human-neuro": {
		name: "Frontiers in Human Neuroscience",
		provider: "rss",
		homeUrl: "https://www.frontiersin.org/journals/human-neuroscience",
		feedUrl: "https://www.frontiersin.org/journals/human-neuroscience/rss",
		refresh: "rss",
	},
	"neuroscience-news": {
		name: "Neuroscience News",
		provider: "rss",
		homeUrl: "https://neurosciencenews.com/",
		feedUrl: "https://neurosciencenews.com/feed/",
		refresh: "rss",
	},
	"science-alert": {
		name: "ScienceAlert",
		provider: "rss",
		homeUrl: "https://www.sciencealert.com/",
		feedUrl: "https://www.sciencealert.com/feed",
		refresh: "rss",
	},
	"reddit-cogsci": {
		name: "r/cogsci",
		provider: "native",
		adapter: "reddit",
		homeUrl: "https://www.reddit.com/r/cogsci/",
		params: { subreddit: "cogsci" },
		refresh: "community",
	},

	// Chinese-language sources
	"zhihu-hot": {
		name: "Zhihu Hot",
		provider: "rsshub",
		homeUrl: "https://www.zhihu.com/hot",
		route: "/zhihu/hot",
		refresh: "hot",
	},
	"ithome-ranking-24h": {
		name: "IT之家 · 24h 热榜",
		provider: "rsshub",
		homeUrl: "https://www.ithome.com/",
		route: "/ithome/ranking/24h",
		refresh: "hot",
	},
	"juejin-hot": {
		name: "Juejin Hot",
		provider: "native",
		adapter: "juejinHot",
		homeUrl: "https://juejin.cn/hot/articles",
		refresh: "community",
	},
	sspai: {
		name: "Sspai",
		provider: "rss",
		homeUrl: "https://sspai.com/",
		feedUrl: "https://sspai.com/feed",
		refresh: "rss",
	},
	"36kr-news": {
		name: "36Kr Latest",
		provider: "rsshub",
		homeUrl: "https://36kr.com/",
		route: "/36kr/news/latest",
		refresh: "community",
	},
	v2ex: {
		name: "V2EX",
		provider: "rss",
		homeUrl: "https://www.v2ex.com/",
		feedUrl: "https://www.v2ex.com/index.xml",
		refresh: "community",
	},
	ifanr: {
		name: "爱范儿",
		provider: "rss",
		homeUrl: "https://www.ifanr.com/",
		feedUrl: "https://www.ifanr.com/feed",
		refresh: "rss",
	},
	appinn: {
		name: "小众软件",
		provider: "rss",
		homeUrl: "https://www.appinn.com/",
		feedUrl: "https://feed.appinn.com/",
		refresh: "rss",
	},
	"ruanyifeng-weekly": {
		name: "阮一峰的网络日志",
		provider: "rss",
		homeUrl: "https://www.ruanyifeng.com/blog/",
		feedUrl: "https://www.ruanyifeng.com/blog/atom.xml",
		refresh: "slow",
	},
	geekpark: {
		name: "极客公园",
		provider: "rsshub",
		homeUrl: "https://www.geekpark.net/",
		route: "/geekpark/breakingnews",
		refresh: "rss",
	},
	baidu: newsnowCnSource("百度热搜", "https://www.baidu.com"),
	"bilibili-hot-search": newsnowCnSource(
		"哔哩哔哩 · 热搜",
		"https://www.bilibili.com"
	),
	"bilibili-hot-video": newsnowCnSource(
		"哔哩哔哩 · 热门视频",
		"https://www.bilibili.com"
	),
	"bilibili-ranking": newsnowCnSource(
		"哔哩哔哩 · 排行榜",
		"https://www.bilibili.com",
		"rss"
	),
	cankaoxiaoxi: newsnowCnSource(
		"参考消息",
		"https://china.cankaoxiaoxi.com",
		"rss"
	),
	"chongbuluo-hot": newsnowCnSource(
		"虫部落 · 最热",
		"https://www.chongbuluo.com/forum.php?mod=guide&view=hot",
		"community"
	),
	"chongbuluo-latest": newsnowCnSource(
		"虫部落 · 最新",
		"https://www.chongbuluo.com/forum.php?mod=guide&view=newthread",
		"community"
	),
	"cls-depth": newsnowCnSource("财联社 · 深度", "https://www.cls.cn", "rss"),
	"cls-hot": newsnowCnSource("财联社 · 热门", "https://www.cls.cn"),
	"cls-telegraph": newsnowCnSource("财联社 · 电报", "https://www.cls.cn"),
	coolapk: newsnowCnSource("酷安 · 今日最热", "https://coolapk.com"),
	douban: newsnowCnSource("豆瓣 · 热门电影", "https://www.douban.com"),
	douyin: newsnowCnSource("抖音热榜", "https://www.douyin.com"),
	"fastbull-express": newsnowCnSource(
		"法布财经 · 快讯",
		"https://www.fastbull.cn"
	),
	"fastbull-news": newsnowCnSource(
		"法布财经 · 头条",
		"https://www.fastbull.cn",
		"rss"
	),
	freebuf: newsnowCnSource("Freebuf · 网络安全", "https://www.freebuf.com/"),
	gelonghui: newsnowCnSource("格隆汇 · 事件", "https://www.gelonghui.com"),
	hupu: newsnowCnSource("虎扑 · 主干道热帖", "https://hupu.com"),
	ifeng: newsnowCnSource("凤凰网 · 热点资讯", "https://www.ifeng.com"),
	"iqiyi-hot-ranklist": newsnowCnSource(
		"爱奇艺 · 热播榜",
		"https://www.iqiyi.com",
		"rss"
	),
	jin10: newsnowCnSource("金十数据", "https://www.jin10.com"),
	kaopu: newsnowCnSource("靠谱新闻", "https://kaopu.news/", "rss"),
	kuaishou: newsnowCnSource("快手热榜", "https://www.kuaishou.com"),
	"mktnews-flash": newsnowCnSource("MKTNews · 快讯", "https://mktnews.net"),
	nowcoder: newsnowCnSource(
		"牛客热榜",
		"https://www.nowcoder.com",
		"community"
	),
	"pcbeta-windows11": newsnowCnSource(
		"远景论坛 · Win11",
		"https://bbs.pcbeta.com",
		"community"
	),
	"qqvideo-tv-hotsearch": newsnowCnSource(
		"腾讯视频 · 热搜榜",
		"https://v.qq.com/"
	),
	solidot: newsnowCnSource("Solidot", "https://solidot.org", "rss"),
	sputniknewscn: newsnowCnSource("卫星通讯社", "https://sputniknews.cn", "rss"),
	"tencent-hot": newsnowCnSource(
		"腾讯新闻 · 综合早报",
		"https://news.qq.com/tag/aEWqxLtdgmQ=",
		"rss"
	),
	thepaper: newsnowCnSource("澎湃新闻 · 热榜", "https://www.thepaper.cn"),
	tieba: newsnowCnSource("百度贴吧 · 热议", "https://tieba.baidu.com"),
	toutiao: newsnowCnSource("今日头条热榜", "https://www.toutiao.com"),
	"wallstreetcn-hot": newsnowCnSource(
		"华尔街见闻 · 最热",
		"https://wallstreetcn.com/",
		"rss"
	),
	"wallstreetcn-news": newsnowCnSource(
		"华尔街见闻 · 最新",
		"https://wallstreetcn.com/",
		"rss"
	),
	"wallstreetcn-quick": newsnowCnSource(
		"华尔街见闻 · 快讯",
		"https://wallstreetcn.com/"
	),
	weibo: newsnowCnSource("微博 · 实时热搜", "https://weibo.com"),
	"xueqiu-hotstock": newsnowCnSource("雪球 · 热门股票", "https://xueqiu.com"),
	zaobao: newsnowCnSource("联合早报", "https://www.zaobao.com", "rss"),
} as const satisfies Record<string, SourcePreset>;

export type SourcePresetId = keyof typeof sourcePresets;

export const sourceNotes = {
	"36kr-news": "Chinese startup and technology business headlines.",
	"9to5mac": "Apple product news, rumors, and ecosystem coverage.",
	adafruit: "Maker hardware tutorials, launches, and community projects.",
	"ant-bailing-blog": "Ant Group Bailing model and developer updates.",
	appinn: "Chinese coverage of useful niche software and apps.",
	"apple-ml-research": "Apple machine learning research papers and notes.",
	"apple-newsroom": "Official Apple product, company, and research news.",
	baidu: "Realtime hot search topics from Baidu.",
	"bilibili-hot-search": "Trending search terms from Bilibili.",
	"bilibili-hot-video": "Popular videos from Bilibili.",
	"bilibili-ranking": "Ranked popular videos from Bilibili.",
	"bytedance-seed": "ByteDance Seed AI research and model updates.",
	cankaoxiaoxi: "Chinese international news from Reference News.",
	"chongbuluo-hot": "Popular Chinese forum threads from Chongbuluo.",
	"chongbuluo-latest": "Latest Chinese forum threads from Chongbuluo.",
	"claude-blog": "Claude product updates and practical announcements.",
	"claude-code-releases": "Version releases for Anthropic Claude Code.",
	"cls-depth": "In-depth finance stories from Cailian Press.",
	"cls-hot": "Popular finance stories from Cailian Press.",
	"cls-telegraph": "Realtime finance updates from Cailian Press.",
	"cloudflare-blog": "Cloudflare engineering and infrastructure posts.",
	"cmu-ml-blog": "Machine learning research notes from Carnegie Mellon.",
	coolapk: "Trending Chinese app and device discussions from Coolapk.",
	"cursor-blog": "Cursor editor product and AI coding updates.",
	"dario-amodei": "Essays and public writing from Dario Amodei.",
	"deepseek-github": "DeepSeek organization activity from GitHub.",
	"descript-blog": "Descript product updates for AI audio and video tools.",
	douban: "Hot movie trends from Douban.",
	douyin: "Hot search trends from Douyin.",
	"dwarkesh-patel": "Dwarkesh Patel podcast episodes and essays.",
	"eleutherai-blog": "EleutherAI open model and research updates.",
	"fastbull-express": "Realtime market updates from FastBull.",
	"fastbull-news": "Finance headlines from FastBull.",
	freebuf: "Chinese cybersecurity articles and threat coverage.",
	"gary-marcus": "Gary Marcus essays on AI reliability and policy.",
	gelonghui: "Chinese finance events and market news.",
	"anthropic-engineering":
		"Official Anthropic engineering posts and technical updates.",
	"anthropic-news": "Official Anthropic product and research updates.",
	"anthropic-research":
		"Official Anthropic research papers and model safety updates.",
	"apnews-technology": "Technology news from the Associated Press.",
	"ars-technica": "Deep reporting on technology, science, and policy.",
	appleinsider: "Apple news, reviews, deals, and ecosystem coverage.",
	"arxiv-cs-ai": "Recent artificial intelligence papers from arXiv.",
	"arxiv-cs-cl": "Recent computational linguistics papers from arXiv.",
	"arxiv-cs-cv": "Recent computer vision papers from arXiv.",
	"arxiv-cs-lg": "Recent machine learning papers from arXiv.",
	"arxiv-cs-ne": "Recent neural and evolutionary computing papers from arXiv.",
	"arxiv-eess-sy": "Recent systems and control papers from arXiv.",
	"arxiv-q-bio-nc": "Recent neuroscience papers from arXiv.",
	"arxiv-robotics": "Recent robotics papers from arXiv.",
	"bair-blog": "Research updates from Berkeley AI Research.",
	"berkeley-rdi": "Berkeley RDI research on AI safety and evaluation.",
	"big-think":
		"Science, cognition, and future-focused essays for general readers.",
	bdtechtalks: "Accessible analysis of AI, robotics, and emerging tech.",
	"bbc-news": "Top international news coverage from the BBC.",
	bloomberg:
		"Bloomberg reporting surfaced through a source-specific news feed.",
	"boston-dynamics": "Company updates on robotics products and deployments.",
	axios: "Concise reporting on politics, business, technology, and media.",
	"business-insider": "Business, technology, markets, and strategy news.",
	"coindesk-news":
		"Mainstream crypto, blockchain, and digital assets coverage.",
	cointelegraph: "Crypto, blockchain, and Web3 market news.",
	crowdsupply: "Open hardware launches and crowdfunding updates.",
	"css-tricks": "Frontend engineering articles focused on CSS and web UI.",
	"cult-of-mac": "Apple product news, how-tos, reviews, and deals.",
	"daily-dev-popular": "Popular developer articles aggregated by daily.dev.",
	"daring-fireball": "Apple-focused commentary and independent tech links.",
	"deepmind-blog": "Research and product updates from Google DeepMind.",
	"deeplearning-the-batch":
		"Accessible AI news and analysis from DeepLearning.AI.",
	devto: "Developer community posts, tutorials, and career stories.",
	economist: "Global economics, politics, business, and culture reporting.",
	"engadget-robotics": "Consumer-friendly robotics coverage from Engadget.",
	engadget: "Consumer technology news and gadget coverage.",
	"financial-times": "Global business, markets, and economic reporting.",
	freecodecamp: "Programming tutorials and developer education articles.",
	"frontiers-human-neuro":
		"Human neuroscience research articles and journal updates.",
	"frontiers-neuroscience":
		"Neuroscience research articles and journal updates.",
	geekpark: "Chinese product, startup, and technology news.",
	"github-blog": "Official GitHub engineering, product, and community updates.",
	"github-trending": "Daily trending repositories across GitHub.",
	"github-trending-weekly": "Weekly trending repositories across GitHub.",
	gizmodo: "Gadget, science, and digital culture coverage.",
	"google-ai-blog": "Google AI product and research announcements.",
	"google-developers-blog": "Google developer platform and API updates.",
	"google-news": "Top global headlines aggregated by Google News.",
	"google-research-blog": "Research updates from Google teams.",
	hupu: "Hot discussion threads from Hupu.",
	hackaday: "Hardware hacking, electronics, and maker projects.",
	hackernews: "Front-page startup and technology discussions.",
	"hackernews-ask": "Ask HN questions and community discussions.",
	"hackernews-best": "Highly ranked Hacker News stories over time.",
	"hackernews-show": "Show HN launches, demos, and side projects.",
	"huggingface-blog": "Hugging Face model, product, and community updates.",
	"huggingface-papers":
		"Daily machine learning papers highlighted by Hugging Face.",
	ifanr: "Chinese consumer tech, products, and lifestyle coverage.",
	ifeng: "Hot Chinese news headlines from Ifeng.",
	"inclusionai-huggingface": "inclusionAI model and organization updates.",
	indiehackers: "Founder stories and independent business discussions.",
	infoq: "Software architecture, engineering leadership, and platform trends.",
	interconnects: "Nathan Lambert's AI industry and research analysis.",
	"iqiyi-hot-ranklist": "Popular shows and videos from iQiyi.",
	"ieee-biomedical": "Biomedical technology coverage from IEEE Spectrum.",
	"ieee-robotics": "Robotics coverage from IEEE Spectrum.",
	"ithome-ranking-24h":
		"Chinese consumer technology headlines from IT Home's 24-hour ranking.",
	"juejin-hot": "Trending Chinese developer articles from Juejin.",
	jin10: "Realtime finance updates from Jin10.",
	kaopu: "Chinese-language curated news from Kaopu.",
	"karpathy-blog": "Long-form AI notes and essays from Andrej Karpathy.",
	"kickstarter-tech": "Technology crowdfunding projects on Kickstarter.",
	"kimi-updates": "Moonshot AI and Kimi product or model updates.",
	kuaishou: "Hot search trends from Kuaishou.",
	"latent-space": "AI engineering essays, interviews, and product analysis.",
	liliputing: "Mobile computing, mini PCs, and portable hardware news.",
	"lilian-weng": "Deep learning research explainers from Lilian Weng.",
	lobsters: "Programming and open source links from Lobsters.",
	"lobsters-ai": "AI-focused discussions from the Lobsters community.",
	"lmsys-blog": "LMSYS and Chatbot Arena research updates.",
	lwn: "Linux, open source, and kernel development coverage.",
	macrumors: "Apple rumors, product news, and buying-guide coverage.",
	"make-magazine": "Maker projects, DIY hardware, and event updates.",
	"meituan-longcat": "Meituan LongCat model updates from public sources.",
	"meta-ai-blog": "Meta AI research and product updates.",
	"meta-engineering": "Meta engineering posts and production lessons.",
	"midjourney-updates": "Midjourney product and model update notes.",
	"minimax-news": "MiniMax model and product news.",
	"mktnews-flash": "Realtime finance updates from MKTNews.",
	"mit-tech-review": "Technology Review coverage of emerging technology.",
	"mit-tech-review-ai": "Technology Review coverage focused on AI.",
	"mit-tech-review-bio": "Technology Review coverage focused on biotech.",
	"mit-news-robotics": "MIT robotics research and lab news.",
	"mozilla-ai": "Mozilla updates on open and trustworthy AI.",
	nature: "Latest research papers and news from Nature.",
	"nature-bmi": "Research updates on brain-machine interfaces.",
	"nature-neuroscience": "Neuroscience research from Nature.",
	"neuroscience-news": "Neuroscience and psychology research news.",
	"new-yorker": "Long-form reporting, essays, criticism, and culture.",
	"new-atlas-robotics":
		"Robotics coverage across research, devices, and unusual machines.",
	nowcoder: "Hot Chinese developer and career discussions from Nowcoder.",
	"nvidia-ai-blog": "NVIDIA AI product, research, and platform updates.",
	"nvidia-blog": "NVIDIA product, AI, GPU, and computing updates.",
	"nvidia-dev-robotics":
		"NVIDIA technical posts on robotics, Jetson, simulation, and edge AI.",
	"nvidia-news-robotics":
		"NVIDIA robotics and physical AI product and partner updates.",
	nytimes: "Top stories and reporting from The New York Times.",
	"openai-cookbook": "Official OpenAI API examples and implementation guides.",
	"openai-academy": "OpenAI Academy tutorials and practice-oriented updates.",
	"openai-alignment": "OpenAI alignment and safety research updates.",
	"openai-news": "Official OpenAI product, research, and company updates.",
	"openai-research": "Official OpenAI research updates and papers.",
	"openrouter-announcements": "OpenRouter model and API announcements.",
	"open-robotics-blog": "Official Open Robotics and OSRA ecosystem updates.",
	"one-useful-thing": "Ethan Mollick essays on practical AI use and education.",
	"pcbeta-windows11": "Windows 11 forum threads from PCBETA.",
	phoronix: "Linux hardware, drivers, and performance news.",
	"phys-org": "Science and technology research news from Phys.org.",
	"planet-ros": "Aggregated ROS ecosystem posts, releases, and discussions.",
	politico: "Politics and policy reporting from Politico.",
	producthunt: "New product launches and maker community trends.",
	"qqvideo-tv-hotsearch": "Popular TV searches from Tencent Video.",
	"qbitai-embodied": "Chinese coverage tagged for embodied AI from QbitAI.",
	"qwen-blog": "Qwen project posts and release notes.",
	"qwen-research": "Qwen model releases and research updates.",
	"quanta-magazine": "Deep science and mathematics features.",
	"reddit-bci": "Community discussions about brain-computer interfaces.",
	"reddit-cogsci": "Cognitive science discussions and research links.",
	"reddit-embedded": "Embedded systems engineering discussions.",
	"reddit-entrepreneur": "Entrepreneurship advice and founder discussions.",
	"reddit-gadgets": "Consumer gadget news and discussion.",
	"reddit-golang": "Go language news and engineering discussions.",
	"reddit-hardware": "PC hardware and component discussions.",
	"reddit-indiehackers": "Independent founder discussions from Reddit.",
	"reddit-localllama": "Local and open model discussions from Reddit.",
	"reddit-machinelearning":
		"Machine learning research and community discussion.",
	"reddit-microsaas": "Small SaaS ideas, launches, and operator discussion.",
	"reddit-neuralink": "Community discussion around Neuralink and neurotech.",
	"reddit-neuroengineering":
		"Neuroengineering research and project discussions.",
	"reddit-neuroscience": "Neuroscience research and community discussion.",
	"reddit-programming": "Programming news and discussion from Reddit.",
	"reddit-raspberrypi": "Raspberry Pi projects and troubleshooting discussion.",
	"reddit-reinforcementlearning": "Reinforcement learning research discussion.",
	"reddit-robotics": "Robotics projects, research, and community discussion.",
	"reddit-rust": "Rust language news and engineering discussion.",
	"reddit-saas": "SaaS founder and operator discussion.",
	"reddit-sideproject": "Side project launches and maker feedback.",
	"reddit-startups": "Startup advice, questions, and founder discussion.",
	"reddit-webdev": "Web development news, tools, and community discussion.",
	reuters: "Reuters reporting surfaced through a source-specific news feed.",
	"robot-report": "Robotics industry news and company updates.",
	"robotics-automation-news":
		"Robotics industry news focused on automation deployments.",
	"robotics-tomorrow": "Robotics and automation industry headlines.",
	robohub: "Robotics research, education, and community stories.",
	"ros-discourse": "ROS community releases, questions, and project updates.",
	"ruanyifeng-weekly": "Chinese weekly notes on technology and software.",
	"runway-changelog": "Runway product feature and release updates.",
	"runway-news": "Runway product, research, and company news.",
	"science-alert": "Science news with neuroscience and health coverage.",
	"sebastian-raschka": "Practical AI and machine learning essays.",
	securityonline: "Cybersecurity news, vulnerabilities, and threat research.",
	"serve-the-home": "Server hardware, homelab, and infrastructure coverage.",
	"servicenow-ai": "ServiceNow enterprise AI product and platform posts.",
	"singularity-hub": "Future-focused coverage of AI, science, and robotics.",
	"simon-willison": "AI, data, and web engineering notes from Simon Willison.",
	"sky-news": "Breaking news and international coverage from Sky News.",
	slashdot: "Classic tech news links and reader discussion.",
	"smashing-mag": "Design and frontend engineering articles.",
	solidot: "Chinese technology and open source news from Solidot.",
	"sam-altman": "Essays and updates from Sam Altman's personal blog.",
	"stackoverflow-blog": "Developer ecosystem, survey, and product updates.",
	sputniknewscn: "Chinese international headlines from Sputnik.",
	sspai: "Chinese productivity, app, and digital lifestyle articles.",
	"suno-blog": "Suno music AI product and company updates.",
	"synced-review": "AI research and industry coverage from Synced.",
	"techcrunch-ai": "TechCrunch coverage focused on artificial intelligence.",
	"techcrunch-robotics": "Startup and venture coverage focused on robotics.",
	techcrunch: "Startup, venture, and technology business news.",
	"techxplore-robotics": "Accessible robotics research and technology news.",
	"tencent-hot": "Aggregated Chinese morning news from Tencent.",
	"tencent-hunyuan": "Tencent Hunyuan model and research updates.",
	"the-atlantic": "Long-form reporting and analysis from The Atlantic.",
	"the-decoder": "AI product, model, and policy news.",
	"the-gradient": "Machine learning research essays and interviews.",
	"the-guardian": "International news and analysis from The Guardian.",
	"the-register": "Enterprise technology news with sharp analysis.",
	"the-verge": "Consumer technology and platform news.",
	"the-verge-ai": "The Verge coverage focused on AI.",
	"the-verge-gadgets": "The Verge coverage focused on gadgets.",
	thepaper: "Hot Chinese news stories from The Paper.",
	"tindie-blog": "Independent hardware maker and marketplace updates.",
	tieba: "Hot discussion topics from Baidu Tieba.",
	"toms-hardware": "PC hardware reviews, news, and component coverage.",
	"tomer-tunguz": "Tomer Tunguz essays on software, data, and venture trends.",
	toutiao: "Hot trending stories from Toutiao.",
	"transformer-circuits": "Anthropic interpretability research articles.",
	v2ex: "Chinese developer and internet community discussions.",
	"venturebeat-ai": "VentureBeat coverage focused on AI products and industry.",
	"wallstreetcn-hot": "Popular finance stories from Wallstreetcn.",
	"wallstreetcn-news": "Latest finance news from Wallstreetcn.",
	"wallstreetcn-quick": "Realtime finance updates from Wallstreetcn.",
	weibo: "Realtime hot search trends from Weibo.",
	wired: "Long-form technology, culture, and science coverage.",
	"wired-science": "Wired coverage focused on science.",
	wsj: "Business, markets, and world news from The Wall Street Journal.",
	"xueqiu-hotstock": "Hot stock rankings from Xueqiu.",
	"xai-news": "Official xAI product and company news.",
	"yahoo-finance": "Market and business headlines from Yahoo Finance.",
	zaobao: "Chinese-language realtime news from Lianhe Zaobao.",
	"zhipu-research": "Zhipu AI research and model updates.",
	"zhihu-hot": "Trending Chinese Q&A topics from Zhihu.",
} as const satisfies Record<SourcePresetId, string>;

// Native adapters scrape ranked lists (front pages, hot lists, trending);
// RSS and RSSHub deliver chronological feeds.
export function getSourceKind(id: SourceId): SourceKind {
	return getSourcePreset(id)?.provider === "native" ? "ranking" : "feed";
}

export function getSourcePreset(id: SourceId): SourcePreset | undefined {
	const preset = (sourcePresets as Record<string, SourcePreset>)[id];
	if (!preset) {
		return;
	}
	return isEventEligibleSource(id)
		? { ...preset, eventEligible: true }
		: preset;
}

export function isEventEligibleSource(id: SourceId | string): boolean {
	return EVENT_ELIGIBLE_SOURCE_IDS.has(id);
}

export function getEventEligibleSourceIds(): string[] {
	return [...EVENT_ELIGIBLE_SOURCE_ID_LIST];
}
